[package]
name = "veyra-occupancy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
veyra-party = { version = "0.1.0", path = "../veyra-party" }
veyra-rule-compiler = { version = "0.1.0", path = "../veyra-rule-compiler" }
veyra-rules = { version = "0.1.0", path = "../veyra-rules" }

[lints]
workspace = true
