[package]
name = "veyra-solver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
veyra-occupancy = { version = "0.1.0", path = "../veyra-occupancy" }
veyra-party = { version = "0.1.0", path = "../veyra-party" }
veyra-pricing = { version = "0.1.0", path = "../veyra-pricing" }
veyra-rule-compiler = { version = "0.1.0", path = "../veyra-rule-compiler" }

[dev-dependencies]
proptest.workspace = true
veyra-rules = { version = "0.1.0", path = "../veyra-rules" }

[lints]
workspace = true
